### ISSUE TITLE
双端观看直播能自动完成，但不能自动领取奖励？？

### ISSUE THREAD

**Issue by KongBaiQAQ** [TheWanderingCoel/BiliBiliHelper#10]

**Comment by TheWanderingCoel** [comment]
提示什么呢？
我这里没有问题的
```
[2020-01-31 19:00:16] - INFO: 检查任务「双端观看直播」
[2020-01-31 19:00:16] - WARNING: 「双端观看直播」奖励已经领取过
[2020-01-31 19:00:16] - INFO: 检查任务「每日签到」
[2020-01-31 19:00:16] - WARNING: 「每日签到」今日已签到过
```

**Comment by KongBaiQAQ** [comment]
我是30号开启的，一天有多次检查每日任务，而31号就只有这次，没有显示领取双端奖励。会不会是检查任务的时候刚好出现发心跳包任务，所以就断了检查？
[2020-01-31 00:48:05] - INFO: 检查每日任务
[2020-01-31 00:48:05] - INFO: 检查任务「每日签到」
[2020-01-31 00:48:05] - INFO: 「每日签到」成功，您已连续签到 22 天，获得 6000点用户经验,4根辣条，
[2020-01-31 00:48:06] - INFO: 向直播间 5430 发送心跳包 (WEB)
[2020-01-31 00:48:06] - INFO: 向直播间 5430 发送心跳包 (APP)

**Comment by TheWanderingCoel** [comment]
日志中是否有出现``检查任务「双端观看直播」``?  
你使用的是Release里的还是自己运行的?

**Comment by KongBaiQAQ** [comment]
我用Release运行的，就是第二种方式那个。
我发现我两个号都是这样，第一天他会自己领取双端奖励，第二天检查每日任务都只有签到

**Comment by TheWanderingCoel** [comment]
试试第一种方式吧,``v0.0.6``修复了挺多bug但是因为没开发完成就没有release出来。

**Comment by TheWanderingCoel** [comment]
如果还是不行的话我看下，这个issues就先不关了。感谢反馈

**Comment by Billyzou0741326** [comment]
第一反应是时间计算有出错的可能性，但测了下没问题...
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/8bd7cb2a2b3f691ee457cc5a6f52bf6647b518a6/Src/Base.py#L83

asyncio.sleep出错的可能性不大 毕竟如果这个坏了那就无了啊23333
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/cdaf96ead9d45c8f08cd8bca9d4f99468680a714/Src/Task.py#L37

最后... 这两个低概率raise Exception
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/cdaf96ead9d45c8f08cd8bca9d4f99468680a714/Src/Task.py#L32-L33

**Comment by Billyzou0741326** [comment]
看了下应该没什么问题  建议运行最新版的源码

**Comment by KongBaiQAQ** [comment]
我用第一种方式会安装失败，即使我安装了python3.6.5他还是会提示不能使用python2.7
阿里云的CentOS 7.7
提示：
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.0.1; however, version 20.0.2 is available.
You should consider upgrading via the '/usr/bin/python2 -m pip install --upgrade pip' command.

**Comment by KongBaiQAQ** [comment]
完整的：
[root@iZ2meniqbt35lbZ BiliBiliHelper]# pip install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://pypi.doubanio.com/simple
Collecting aiohttp
  Downloading https://pypi.doubanio.com/packages/00/94/f9fa18e8d7124d7850a5715a0b9c0584f7b9375d331d35e157cee50f27cc/aiohttp-3.6.2.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 1.6 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-DySdzd/aiohttp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-DySdzd/aiohttp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-DySdzd/aiohttp/pip-egg-info
         cwd: /tmp/pip-install-DySdzd/aiohttp/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-DySdzd/aiohttp/setup.py", line 23
        print("Install submodules when building from git clone", file=sys.stderr)
                                                                     ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by KongBaiQAQ** [comment]
如果是使用宝塔软件的python项目管理器，启动方式为python
会不断显示这个：
 ＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿ 
|　欢迎使用本控制台　　　　　　|
|１输出本次的参与抽奖统计　　　|
|２查看目前拥有礼物的统计　　　|
|３查看持有勋章状态　　　　　　|
|４获取直播个人的基本信息　　　|
|５检查今日任务的完成情况　　　|
|６模拟电脑网页端发送弹幕　　　|
|７直播间的长短号码的转化　　　|
|８手动送礼物到指定直播间　　　|
|９房间号码查看主播　　　　　　|
|１０当前拥有的扭蛋币　　　　　|
|１１开扭蛋币　　　　　　　　　|
|１２退出软件　　　　　　　　　|
 ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣

**Comment by Billyzou0741326** [comment]
`pip3 install -r requirements.txt`
`python3 main.py`

**Comment by KongBaiQAQ** [comment]
原来是这样，感谢大佬。嘿嘿嘿

**Comment by Billyzou0741326** [comment]
客气了2333

**Comment by TheWanderingCoel** [comment]
> |４获取直播个人的基本信息　　　|

如果用service启动也会这样，我看看有时间加一个参数可以不开启这种命令行。

**Comment by KongBaiQAQ** [comment]
为什么用systemd 脚本挂还是会显示  欢迎使用本控制台　这些东西？
而且CPU占用率百分百
但是在文件日记显示是正常挂机的。
如果  python3 main.py  启动显示和CPU占用是正常的。
现在只能用screen来放到后台了。看看大佬们什么时候有时间看看代码了嘿嘿嘿。哦对，如果升级更新的话是不是只能git覆盖更新？

**Comment by TheWanderingCoel** [comment]
> 为什么用systemd 脚本挂还是会显示 欢迎使用本控制台　这些东西？
> 而且CPU占用率百分百
> 但是在文件日记显示是正常挂机的。
> 如果 python3 main.py 启动显示和CPU占用是正常的。
> 现在只能用screen来放到后台了。看看大佬们什么时候有时间看看代码了嘿嘿嘿。哦对，如果升级更新的话是不是只能git覆盖更新？

我想说的就是这个，下个commit会禁用掉service里的控制台。  
先暂时用screen吧。  
升级更新的话只能``git pull origin master``, 不建议pulll dev。  
也可以使用docker版本

**Comment by TheWanderingCoel** [comment]
是否还在复现？

**Comment by TheWanderingCoel** [comment]
Closed due to inactivity. If you have any issue, feel free to reopen it.
