### ISSUE TITLE
没有guard或guard已领取，抓取data数据显示“请升级app”

### ISSUE THREAD

**Issue by Sonic853** [TheWanderingCoel/BiliBiliHelper#16]
在 BasicRequest.guard_req_check 获取返回的data数据显示该信息

**Comment by Billyzou0741326** [comment]
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/e2881324838575751382c41a113bb47dddf6ec84/Src/BasicRequest.py#L75-L76

**Comment by Billyzou0741326** [comment]
76行修改为 
```python
    url = 'https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join'
```

**Comment by Sonic853** [comment]
> 76行修改为
> 
> ```python
>         url = 'https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join'
> ```

修改了，不过造成这个问题的是出在guard_req_check上，76行修改的是guard_req_join那边。

**Comment by TheWanderingCoel** [comment]
``[2020-02-20 19:09:08] [WARNING] 5351443 没有guard或guard已领取``。看到了，我去修改一下api。感谢反馈

**Comment by Billyzou0741326** [comment]
诶 我指挥错了 抱歉抱歉2333

**Comment by Sonic853** [comment]
> `[2020-02-20 19:09:08] [WARNING] 5351443 没有guard或guard已领取`。看到了，我去修改一下api。感谢反馈

目前我的解决方案为：
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/e2881324838575751382c41a113bb47dddf6ec84/Src/BasicRequest.py#L69-L70
将第70行改为：
```Python
url = "https://api.live.bilibili.com/xlive/lottery-interface/v1/lottery/Check?roomid=%s" % real_roomid
```
改完上面后在Guard_Raffle_Handler.py第33行：
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/e2881324838575751382c41a113bb47dddf6ec84/Src/Guard_Raffle_Handler.py#L33
改为：
```Python
if data["data"]["guard"]:
```
在42行：
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/e2881324838575751382c41a113bb47dddf6ec84/Src/Guard_Raffle_Handler.py#L42
改为：
```Python
for j in data["data"]["guard"]:
```
目前改完后在我这里是能够正常运行的。

**Comment by TheWanderingCoel** [comment]
十分感谢。看样子b站把整个guard的chekc接口删掉了
