### ISSUE TITLE
脚本不会每天签到？？

### ISSUE THREAD

**Issue by KongBaiQAQ** [TheWanderingCoel/BiliBiliHelper#18]
**介绍一下这个Bug**

脚本第一次启动会检查是否签到，但是第二天开始之后就不会检查，导致没有签到

而且奇怪的是，以前是没有这种情况，是突然这样的，
好像是某次重启会这样，然后我尝试过重启，重装也有这样的问题

阿里云的学生机
Centos 7.7

**Comment by KongBaiQAQ** [comment]
补充一下，我挂小号的另一个阿里云也是这样。
2号开始没有签到，然后到8号重装
但17号开始到21号又没有签到（8号到17号都签到了），很奇怪，期间没有对服务器进行操作

**Comment by Billyzou0741326** [comment]
想问下 21号的双端观看完成了吗？

每日任务的重置（签到、双端）需要两个任务都完成的 其中一个未完成的话次日也不会重置（算是bug了） 确认一下昨天的双端是不是没完成

**Comment by Billyzou0741326** [comment]
分析出来的结果是有几处地方可能对签到产生影响

## 1. Task Info API 检查签到状态
<https://api.live.bilibili.com/i/api/taskInfo>的`data['sign_info']['status']`在签到完成后仍是0
解决方案: <https://api.live.bilibili.com/sign/GetSignInfo> 取data['status']

## 2. 每日任务重置的触发条件
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/81178587f4b83e459bfa8c0fdb21b7c023775506/Src/Task.py#L35-L39
仅在签到&双端完成后等待凌晨重置，如果没能全部完成，会无限等待下去而不执行重置
解决方案: async多线并行，等待凌晨的同时执行持续双端

## 3. 双端观看判定策略变更
b站这几天的双端观看不能仅凭发送心跳完成了，需要发送一次`getInfoByUser`的API请求
解决方案: 
### Web (GET)
api.live.bilibili.com/xlive/web-room/v1/index/getInfoByUser
| param key         | param value   |
|-------------------|---------------|
| room_id            |                      |
### App (GET)
api.live.bilibili.com/xlive/app-room/v1/index/getInfoByUser
| param key         | param value   |
|-------------------|---------------|
| access_key        |               |
| actionKey         |               |
| appKey            |               |
| build             |               |
| channel           | bili          |
| device            | android       |
| mobi_app          | android       |
| platform          | android       |
| room_id           |               |
| statistics        |               |
| ts                |               |
| sign              |               |

**Comment by KongBaiQAQ** [comment]
> 想问下21号的双端观看完成了吗？
> 
> 每日任务的重置（签到，双端）需要两个任务都完成的其中一个未完成的话次次日也不会重置（算是错误了）确认一下昨天的双端是不是没完成

是的，一直提示未完成双端任务。。。
你这个对于我这种小白来说有点懵，我明天再研究研究

**Comment by Billyzou0741326** [comment]
> 是的，一直提示未完成双端任务。。。
> 你这个对于我这种小白来说有点懵，我明天再研究研究

这个分析是为后续的代码修改做铺垫的hhh 无视就好
确认了没完成双端的话那就好办了（应该）
