### ISSUE TITLE
运行报错问题

### ISSUE THREAD

**Issue by MaxSecurity** [TheWanderingCoel/BiliBiliHelper#2]
报错信息：
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    Auth.work()
  File "Src\Auth.py", line 32, in work
    self.loginToken()
  File "Src\Auth.py", line 50, in loginToken
    if self.checkToken() == False:
  File "Src\Auth.py", line 75, in checkToken
    data = Curl().request_json("GET",url,headers=config["pcheaders"],params=payload)
  File "Src\Curl.py", line 15, in __init__
    if config["Proxy"]["PROXY_TYPE"] != "None":
  File "D:\Python37\lib\site-packages\configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'Proxy'

**Comment by TheWanderingCoel** [comment]
能否把``BiliBiliHelper.conf``发上来看一下,先用``Clean.py``去除下隐私信息（账号,密码,cookie)。

**Comment by MaxSecurity** [comment]
好的！如下！
[Account]
BILIBILI_USER =xxxx
BILIBILI_PASSWORD = xxxxxx

[Token]
ACCESS_TOKEN = 59fxxxx1cda91
REFRESH_TOKEN = 8cbe0e34xxxxx8c0ef38601391
CSRF = 9b6cc6xxxxx0fbb9dfd94
UID = xxxx
COOKIE = bili_jct=9b6cc66dd01xxxx4;DedeUserID=1xxxx7;DedeUserID__ckMd5=b9039xxxxf;sid=9rrkrbk4;SESSDATA=1d0f7dab%2C15709xxxxxxx6b3791;

[Function]
CAPSULE = True
COIN2SILVER = True
GIFTSEND = True
GROUP = True
SILVER2COIN = True
SILVERBOX = True
TASK = True
RAFFLE_HANDLER = True

[Coin2Silver]
COIN = 1

[Live]
ROOM_ID = https://live.bilibili.com/11923820

[Raffle_Handler]
TV = True
GUARD = True
STORM = True

[Log]
LOG_LEVEL = info

[Other]
INFO_MESSAGE = True
SENTENCE = True

[pcheaders]
Accept = "application/json, text/plain, */*"
User-Agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
Accept-Language = "zh-CN,zh;q=0.9"
accept-encoding = "gzip, deflate"
cookie = bili_jct=9b6cc66dd01f43cd49d8550fbb9dfd94;DedeUserID=1822477;DedeUserID__ckMd5=b90399f1d885d21f;sid=9rrkrbk4;SESSDATA=1d0f7dab%2C1570945665%2C846b3791;

**Comment by TheWanderingCoel** [comment]
请对照下新的那个conf文件加入``Proxy``这一块的设置。还有你的那个ROOM_ID直接是房间号就行,不需要整个url.

**Comment by MaxSecurity** [comment]
好的感谢
