### ISSUE TITLE
大航海之后总会跟一句绿色的错误

### ISSUE THREAD

**Issue by KillingNights** [TheWanderingCoel/BiliBiliHelper#22]
**介绍一下这个Bug**
这个Bug的具体的表现
[2020-03-01 09:29:53,334] - INFO: {'code': 1000002, 'msg': '控制器lottery\\frontend\\controller\\v3\\C_Lottery未找到', 'message': '控制器lottery\\frontend\\controller\\v3\\C_Lottery未找到', 'data': {}}
**如何复现?**

**你期待的表现**
清楚介绍您希望的结果。

**截图**
如果合适,请您附上截图

**系统环境 (请完成以下填入):**
 - 系统 [windows]
 - Python 版本 [3.6.4]

**额外信息**
任何额外的信息都可以在这里输入

**Comment by TheWanderingCoel** [comment]
接口换了，有时间改下。

**Comment by luoshuijs** [comment]
我替大佬换一下，自己魔改了一下。大概就是这样。
在`Src/BasicRequest.py`第67行
```` 
    # 大航海请求
    @staticmethod
    async def guard_req_check(real_roomid):
        url = "https://api.live.bilibili.com/xlive/lottery-interface/v1/lottery/Check?roomid=%s" % real_roomid
        response = await AsyncioCurl().request_json("GET", url, headers=config["pcheaders"])
        return response
    @staticmethod
    async def guard_req_join(real_roomid, raffle_id):
        url = "https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join"
        payload = {
            "roomid": real_roomid,
            "id": raffle_id,
            "type": "guard",
            "csrf_token": account["Token"]["CSRF"],
            "csrf": account["Token"]["CSRF"]
        }
        response = await AsyncioCurl().request_json("POST", url, data=payload, headers=config["pcheaders"])
        return response
````
当时我还以为换了就完事了，最想不到出了错误。
晕了，居然还有统计接口也得换。
研究了一下大概返回的数据就是这滴。
````
{
	'code': 0,
	'data': {
		'id': 2250566,//房间ID
		'award_id': 1,//礼物ID
		'award_type': 0,//礼物类型
		'award_num': 1,//礼物数量
		'award_image': 'http://i0.hdslb.com/bfs/live/d57afb7c5596359970eb430655c6aef501a268ab.png',//礼物图片
		'award_name': '辣条',//礼物名称
		'award_text': '',//礼物信息
		'award_ex_time': 1585756800//获取时间
	},
	'message': 'ok',//状态
	'msg': 'ok'//和上面一样
}
````
修改一下。
在`Src/Guard_Raffle_Handler.py`第60行
````
    @staticmethod
    async def join(num, real_roomid, raffle_id):
        await asyncio.sleep(random.uniform(0.5, min(30, num * 1.3)))
        data = await BasicRequest.guard_req_join(real_roomid, raffle_id)
        Log.raffle("参与了房间 %s 的大航海抽奖" % (real_roomid))
        print(data)
        if not data["code"]:
            Statistics.add2results(data["data"]["award_name"], data["data"]["award_num"])
            Log.raffle("房间 %s 大航海抽奖结果: %s" % (real_roomid, data["message"]))
            Statistics.add2joined_raffles("大航海(合计)")
        else:
            Log.info(data)
````
估计统计接口是这样调用的，毕竟我也不知道原来接口是返回什么样的数据了emmmm。
我仔细观察了一下，现在B站对这类大航海的调用后直接返回获得的礼物，应该不用调用`guard_req_check`去检查是否获取到了。
大佬我很喜欢你这个脚本（至少不像隔壁看到我头都疼了2333），希望以后继续维护，加油！

**Comment by Billyzou0741326** [comment]
总结一下
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/8b0060abc5e2e9c501bb1d01116b08bf66b410dc/Src/BasicRequest.py#L76
API更新为 `url = https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join`

https://github.com/TheWanderingCoel/BiliBiliHelper/blob/8b0060abc5e2e9c501bb1d01116b08bf66b410dc/Src/Guard_Raffle_Handler.py#L66-L68
替换 `Statistics.add2results(data["data"]["award_name"], data["data"]["award_num"])`

pk、smalltv、anchor那些都没问题
@luoshuijs 有意向的话可以提交个pull request

**Comment by luoshuijs** [comment]
@Billyzou0741326 
如果有空我去pull request（大概），<del>毕竟刚刚瞟了一眼代码就上头了。</del>明天还得上课（困）

**Comment by luoshuijs** [comment]
由于一些原因，似乎`guard_req_check`也得改里面的url....不然就会出现像这边 [WARNING: 21708167 没有guard或guard已领取](https://github.com/TheWanderingCoel/BiliBiliHelper/issues/20) 一样的错误。
毕竟check的功能还在运行

**Comment by Billyzou0741326** [comment]
check没变，这个大概率是服务端重启程序导致重复播报之前的舰长信息...

**Comment by luoshuijs** [comment]
希望如此，大概开学莫得空去研究大佬的代码了，估计等功能完善可能都毕业了（bushi）。

**Comment by TheWanderingCoel** [comment]
感谢二位 @luoshuijs @Billyzou0741326
