### ISSUE TITLE
使用一段时间的建议

### ISSUE THREAD

**Issue by Zhou-Yanlin** [TheWanderingCoel/BiliBiliHelper#23]
1.主站的经验的每日奖励
        希望添加完成每日登录、每日观看视频以及每日分享视频(客户端)。前两个应该很好完成吧，估计就是一个请求过去就算完成吧（猜的），每日分享视频(客户端)可以直接分享到b站动态，不会掉用其他地方的api，亲测每天转发同一个视频是可以的，觉得碍事应该可以删掉（这个没试过）。
2.完成双端观看直播任务（可能是个bug）
        检测好多遍都说未完成，但看程序有发web和app的心跳包，不知道是不是因为设置的房间没开播（我设置的1好直播间，长号5440），如果是没开播的话建议在直播签到时一并寻找一个开播的up然后对其房间发送心跳包。

最后，真的超级感谢作者！！（doge

**Comment by Billyzou0741326** [comment]
第二点确实是bug https://github.com/TheWanderingCoel/BiliBiliHelper/issues/18#issuecomment-589767239_
最近有点忙 什么时候闲了改下...

**Comment by TheWanderingCoel** [comment]
好的，有时间改下（可能基本没时间）。感谢 @Billyzou0741326 回复hhh
