### ISSUE TITLE
ERROR: 无法连接到舰长监控服务器,请检查网络连接以及端口是否开放

### ISSUE THREAD

**Issue by ValentinoLee** [TheWanderingCoel/BiliBiliHelper#26]
**介绍一下这个Bug**
这个Bug的具体的表现

**如何复现?**

**你期待的表现**
清楚介绍您希望的结果。

**截图**
如果合适,请您附上截图

**系统环境 (请完成以下填入):**
 - 系统 [win10]
 - Python 版本 [3.6.5]

**额外信息**
任何额外的信息都可以在这里输入

**Comment by TheWanderingCoel** [comment]
你需要自己搭建一个舰长服务器，如果不需要舰长亲密度可以无视

**Comment by ValentinoLee** [comment]
懂了
