### ISSUE TITLE
请升级app

### ISSUE THREAD

**Issue by ErazerQDY** [TheWanderingCoel/BiliBiliHelper#3]
[2019-10-31 09:29:28,261] - Windows_Log.py[line:64] - INFO: 向直播间  发送心跳包 (WEB)
[2019-10-31 09:29:28,495] - Windows_Log.py[line:64] - INFO: 向直播间  发送心跳包 (APP)
[2019-10-31 09:30:38,196] - Windows_Log.py[line:85] - CRITICAL: 4 号弹幕监控检测到 764155 的 1 个 小电视飞船
[2019-10-31 09:30:38,297] - Windows_Log.py[line:85] - CRITICAL: 5 号弹幕监控检测到 764155 的 1 个 小电视飞船
[2019-10-31 09:30:38,399] - Windows_Log.py[line:85] - CRITICAL: 2 号弹幕监控检测到 764155 的 1 个 小电视飞船
[2019-10-31 09:30:38,500] - Windows_Log.py[line:85] - CRITICAL: 6 号弹幕监控检测到 764155 的 1 个 小电视飞船
[2019-10-31 09:30:38,600] - Windows_Log.py[line:85] - CRITICAL: 3 号弹幕监控检测到 764155 的 1 个 小电视飞船
[2019-10-31 09:30:38,701] - Windows_Log.py[line:85] - CRITICAL: 1 号弹幕监控检测到 764155 的 1 个 小电视飞船
[2019-10-31 09:30:40,541] - Windows_Log.py[line:64] - INFO: 抽奖脚本检测到房间 764155 为正常房间
[2019-10-31 09:30:40,715] - Windows_Log.py[line:64] - INFO: 本次获取到 小电视飞船 的抽奖id为: 459955
[2019-10-31 09:32:37,997] - Windows_Log.py[line:64] - INFO: 参与了房间 764155 的 小电视飞船 抽奖
[2019-10-31 09:32:38,098] - Windows_Log.py[line:64] - INFO: 小电视飞船 抽奖状态: 请升级APP版本

**Comment by TheWanderingCoel** [comment]
B站对接口进行了更新,新接口是：
```
POST https://api.live.bilibili.com/xlive/lottery-interface/v5/smalltv/join
{
"id":"xxxxx",
"roomid":"xxxxx",
"type":"small_tv",
"csrf_token":"xxxx",
"csrf":"xxxx",
"visit_id":""
}
```
将在有空时进行一次更新,感谢反馈

**Comment by TheWanderingCoel** [comment]
应该修复了

**Comment by homolive114514** [comment]
最近同样被要求升级APP版本，我把最新更新的几个文件替换了一下还是有这个问题...

**Comment by TheWanderingCoel** [comment]
诶...?收到了,我在看一下,实在抱歉

**Comment by TheWanderingCoel** [comment]
> 最近同样被要求升级APP版本，我把最新更新的几个文件替换了一下还是有这个问题...

我这里没有这个问题诶,能否麻烦下使用``git pull origin master``拉取最新文件一下看看?  
或者重新克隆一下这个项目?``git clone https://github.com/TheWanderingCoel/BiliBiliHelper.git``  
```
[2019-11-04 11:53:49]  - Src/Unix_Log.py[Line:66] - CRITICAL: 6 号弹幕监控检测到 21666995 的 舰长
[2019-11-04 11:53:51]  - Src/Unix_Log.py[Line:39] - INFO: 抽奖脚本检测到房间 21666995 为正常房间
[2019-11-04 11:53:51]  - Src/Unix_Log.py[Line:39] - INFO: 本次获取到的 大航海 抽奖id为 1628271
[2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:39] - INFO: 参与了房间 21666995 的大航海抽奖
[2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:66] - CRITICAL: 房间 21666995 大航海抽奖结果: 当前佩戴的粉丝勋章亲密度+1
[2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:39] - INFO: 开始宝箱成功,获得 30 个银瓜子,当前有 4084 个银瓜子
[2019-11-04 11:54:08]  - Src/Unix_Log.py[Line:39] - INFO: 领取宝箱成功,内含 80 个瓜子
[2019-11-04 11:54:08]  - Src/Unix_Log.py[Line:39] - INFO: 等待 6 分钟后打开宝箱
[2019-11-04 11:55:30]  - Src/Unix_Log.py[Line:39] - INFO: 向直播间  发送心跳包 (WEB)
[2019-11-04 11:55:31]  - Src/Unix_Log.py[Line:39] - INFO: 向直播间  发送心跳包 (APP)
[2019-11-04 11:55:51]  - Src/Unix_Log.py[Line:66] - CRITICAL: 房间 9905913 摩天大楼 抽奖结果: 辣条 X 1
娱乐区广播：<%栗深林曦惊层巅%>投喂:<%栗子酱酱酱酱酱酱%>1个摩天大楼，点击前往TA的房间去抽奖吧
[2019-11-04 11:59:20]  - Src/Unix_Log.py[Line:66] - CRITICAL: 1 号弹幕监控检测到 2106735 的 1 个 摩天大楼
[2019-11-04 11:59:23]  - Src/Unix_Log.py[Line:39] - INFO: 抽奖脚本检测到房间 2106735 为正常房间
[2019-11-04 11:59:23]  - Src/Unix_Log.py[Line:39] - INFO: 本次获取到 摩天大楼 的抽奖id为: 463036
[2019-11-04 12:00:21]  - Src/Unix_Log.py[Line:39] - INFO: 参与了房间 2106735 的 摩天大楼 抽奖
[2019-11-04 12:00:21]  - Src/Unix_Log.py[Line:39] - INFO: 摩天大楼 抽奖状态: OK
```

**Comment by ErazerQDY** [comment]
> 诶...?收到了,我在看一下,实在抱歉

怎么才可以检测到风暴（小声比比）

**Comment by TheWanderingCoel** [comment]
> > 诶...?收到了,我在看一下,实在抱歉
> 
> 怎么才可以检测到风暴（小声比比）

节奏风暴因为只有20倍才会全区广播,单倍的应该只有本房间内才有广播。我也没遇到过几个...

**Comment by ErazerQDY** [comment]
> > > 诶...?收到了,我在看一下,实在抱歉
> > 
> > 
> > 怎么才可以检测到风暴（小声比比）
> 
> 节奏风暴因为只有20倍才会全区广播,单倍的应该只有本房间内才有广播。我也没遇到过几个...

算了，反正在黑屋，不指望了

**Comment by Peucha** [comment]
> > 最近同样被要求升级APP版本，我把最新更新的几个文件替换了一下还是有这个问题...
> 
> 我这里没有这个问题诶,能否麻烦下使用`git pull origin master`拉取最新文件一下看看?
> 或者重新克隆一下这个项目?`git clone https://github.com/TheWanderingCoel/BiliBiliHelper.git`
> 
> ```
> [2019-11-04 11:53:49]  - Src/Unix_Log.py[Line:66] - CRITICAL: 6 号弹幕监控检测到 21666995 的 舰长
> [2019-11-04 11:53:51]  - Src/Unix_Log.py[Line:39] - INFO: 抽奖脚本检测到房间 21666995 为正常房间
> [2019-11-04 11:53:51]  - Src/Unix_Log.py[Line:39] - INFO: 本次获取到的 大航海 抽奖id为 1628271
> [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:39] - INFO: 参与了房间 21666995 的大航海抽奖
> [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:66] - CRITICAL: 房间 21666995 大航海抽奖结果: 当前佩戴的粉丝勋章亲密度+1
> [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:39] - INFO: 开始宝箱成功,获得 30 个银瓜子,当前有 4084 个银瓜子
> [2019-11-04 11:54:08]  - Src/Unix_Log.py[Line:39] - INFO: 领取宝箱成功,内含 80 个瓜子
> [2019-11-04 11:54:08]  - Src/Unix_Log.py[Line:39] - INFO: 等待 6 分钟后打开宝箱
> [2019-11-04 11:55:30]  - Src/Unix_Log.py[Line:39] - INFO: 向直播间  发送心跳包 (WEB)
> [2019-11-04 11:55:31]  - Src/Unix_Log.py[Line:39] - INFO: 向直播间  发送心跳包 (APP)
> [2019-11-04 11:55:51]  - Src/Unix_Log.py[Line:66] - CRITICAL: 房间 9905913 摩天大楼 抽奖结果: 辣条 X 1
> 娱乐区广播：<%栗深林曦惊层巅%>投喂:<%栗子酱酱酱酱酱酱%>1个摩天大楼，点击前往TA的房间去抽奖吧
> [2019-11-04 11:59:20]  - Src/Unix_Log.py[Line:66] - CRITICAL: 1 号弹幕监控检测到 2106735 的 1 个 摩天大楼
> [2019-11-04 11:59:23]  - Src/Unix_Log.py[Line:39] - INFO: 抽奖脚本检测到房间 2106735 为正常房间
> [2019-11-04 11:59:23]  - Src/Unix_Log.py[Line:39] - INFO: 本次获取到 摩天大楼 的抽奖id为: 463036
> [2019-11-04 12:00:21]  - Src/Unix_Log.py[Line:39] - INFO: 参与了房间 2106735 的 摩天大楼 抽奖
> [2019-11-04 12:00:21]  - Src/Unix_Log.py[Line:39] - INFO: 摩天大楼 抽奖状态: OK
> ```

我把原来的文件删了重新指令了一遍还是这个问题...我用下载的bilibilihelper.exe打开提示要升级APP版本，直接用python main.py就是直接闪退和以下的错误
$ python main.py
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    Log.clean_log(startup=True)
  File "Src\Windows_Log.py", line 98, in clean_log
    open(os.getcwd()+"/Log/BiliBiliHelper.log", 'w').close()
NameError: name 'os' is not defined

以前都是可以打开main.py的现在突然闪退不行了...

**Comment by Peucha** [comment]
> > 最近同样被要求升级APP版本，我把最新更新的几个文件替换了一下还是有这个问题...
> 
> 我这里没有这个问题诶,能否麻烦下使用`git pull origin master`拉取最新文件一下看看?
> 或者重新克隆一下这个项目?`git clone https://github.com/TheWanderingCoel/BiliBiliHelper.git`
> 
> ```
> [2019-11-04 11:53:49]  - Src/Unix_Log.py[Line:66] - CRITICAL: 6 号弹幕监控检测到 21666995 的 舰长
> [2019-11-04 11:53:51]  - Src/Unix_Log.py[Line:39] - INFO: 抽奖脚本检测到房间 21666995 为正常房间
> [2019-11-04 11:53:51]  - Src/Unix_Log.py[Line:39] - INFO: 本次获取到的 大航海 抽奖id为 1628271
> [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:39] - INFO: 参与了房间 21666995 的大航海抽奖
> [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:66] - CRITICAL: 房间 21666995 大航海抽奖结果: 当前佩戴的粉丝勋章亲密度+1
> [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:39] - INFO: 开始宝箱成功,获得 30 个银瓜子,当前有 4084 个银瓜子
> [2019-11-04 11:54:08]  - Src/Unix_Log.py[Line:39] - INFO: 领取宝箱成功,内含 80 个瓜子
> [2019-11-04 11:54:08]  - Src/Unix_Log.py[Line:39] - INFO: 等待 6 分钟后打开宝箱
> [2019-11-04 11:55:30]  - Src/Unix_Log.py[Line:39] - INFO: 向直播间  发送心跳包 (WEB)
> [2019-11-04 11:55:31]  - Src/Unix_Log.py[Line:39] - INFO: 向直播间  发送心跳包 (APP)
> [2019-11-04 11:55:51]  - Src/Unix_Log.py[Line:66] - CRITICAL: 房间 9905913 摩天大楼 抽奖结果: 辣条 X 1
> 娱乐区广播：<%栗深林曦惊层巅%>投喂:<%栗子酱酱酱酱酱酱%>1个摩天大楼，点击前往TA的房间去抽奖吧
> [2019-11-04 11:59:20]  - Src/Unix_Log.py[Line:66] - CRITICAL: 1 号弹幕监控检测到 2106735 的 1 个 摩天大楼
> [2019-11-04 11:59:23]  - Src/Unix_Log.py[Line:39] - INFO: 抽奖脚本检测到房间 2106735 为正常房间
> [2019-11-04 11:59:23]  - Src/Unix_Log.py[Line:39] - INFO: 本次获取到 摩天大楼 的抽奖id为: 463036
> [2019-11-04 12:00:21]  - Src/Unix_Log.py[Line:39] - INFO: 参与了房间 2106735 的 摩天大楼 抽奖
> [2019-11-04 12:00:21]  - Src/Unix_Log.py[Line:39] - INFO: 摩天大楼 抽奖状态: OK
> ```

[2019-11-05 04:07:10,676] - Windows_Log.py[line:85] - CRITICAL: 3 号弹幕监控检测到 1186551 的 1 个 小电视飞船
[2019-11-05 04:07:10,777] - Windows_Log.py[line:85] - CRITICAL: 2 号弹幕监控检测到 1186551 的 1 个 小电视飞船
[2019-11-05 04:07:10,878] - Windows_Log.py[line:85] - CRITICAL: 1 号弹幕监控检测到 1186551 的 1 个 小电视飞船
[2019-11-05 04:07:10,978] - Windows_Log.py[line:85] - CRITICAL: 5 号弹幕监控检测到 1186551 的 1 个 小电视飞船
[2019-11-05 04:07:11,079] - Windows_Log.py[line:85] - CRITICAL: 4 号弹幕监控检测到 1186551 的 1 个 小电视飞船
[2019-11-05 04:07:11,180] - Windows_Log.py[line:85] - CRITICAL: 6 号弹幕监控检测到 1186551 的 1 个 小电视飞船
[2019-11-05 04:07:14,071] - Windows_Log.py[line:64] - INFO: 抽奖脚本检测到房间 1186551 为正常房间
[2019-11-05 04:07:14,451] - Windows_Log.py[line:64] - INFO: 本次获取到 小电视飞船 的抽奖id为: 463516
[2019-11-05 04:08:53,880] - Windows_Log.py[line:64] - INFO: 开始宝箱成功,获得 190 个银瓜子,当前有 169682 个银瓜子
[2019-11-05 04:09:00,831] - Windows_Log.py[line:85] - CRITICAL: 6 号弹幕监控检测到 6154037 的 1 个 摩天大楼
[2019-11-05 04:09:03,435] - Windows_Log.py[line:64] - INFO: 抽奖脚本检测到房间 6154037 为正常房间
[2019-11-05 04:09:03,807] - Windows_Log.py[line:64] - INFO: 本次获取到 摩天大楼 的抽奖id为: 463517
[2019-11-05 04:09:05,837] - Windows_Log.py[line:64] - INFO: 今天所有的宝箱已经领完!
[2019-11-05 04:09:11,242] - Windows_Log.py[line:64] - INFO: 参与了房间 1186551 的 小电视飞船 抽奖
[2019-11-05 04:09:11,343] - Windows_Log.py[line:64] - INFO: 小电视飞船 抽奖状态: 请升级APP版本
[2019-11-05 04:09:44,844] - Windows_Log.py[line:64] - INFO: 向直播间  发送心跳包 (WEB)
[2019-11-05 04:09:45,474] - Windows_Log.py[line:64] - INFO: 向直播间  发送心跳包 (APP)
[2019-11-05 04:10:01,437] - Windows_Log.py[line:64] - INFO: 参与了房间 6154037 的 摩天大楼 抽奖
[2019-11-05 04:10:01,538] - Windows_Log.py[line:64] - INFO: 摩天大楼 抽奖状态: 请升级APP版本
[2019-11-05 04:14:45,802] - Windows_Log.py[line:64] - INFO: 向直播间  发送心跳包 (WEB)
[2019-11-05 04:14:46,172] - Windows_Log.py[line:64] - INFO: 向直播间  发送心跳包 (APP)

**Comment by TheWanderingCoel** [comment]
Release的

> > > 最近同样被要求升级APP版本，我把最新更新的几个文件替换了一下还是有这个问题...
> > 
> > 
> > 我这里没有这个问题诶,能否麻烦下使用`git pull origin master`拉取最新文件一下看看?
> > 或者重新克隆一下这个项目?`git clone https://github.com/TheWanderingCoel/BiliBiliHelper.git`
> > ```
> > [2019-11-04 11:53:49]  - Src/Unix_Log.py[Line:66] - CRITICAL: 6 号弹幕监控检测到 21666995 的 舰长
> > [2019-11-04 11:53:51]  - Src/Unix_Log.py[Line:39] - INFO: 抽奖脚本检测到房间 21666995 为正常房间
> > [2019-11-04 11:53:51]  - Src/Unix_Log.py[Line:39] - INFO: 本次获取到的 大航海 抽奖id为 1628271
> > [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:39] - INFO: 参与了房间 21666995 的大航海抽奖
> > [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:66] - CRITICAL: 房间 21666995 大航海抽奖结果: 当前佩戴的粉丝勋章亲密度+1
> > [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:39] - INFO: 开始宝箱成功,获得 30 个银瓜子,当前有 4084 个银瓜子
> > [2019-11-04 11:54:08]  - Src/Unix_Log.py[Line:39] - INFO: 领取宝箱成功,内含 80 个瓜子
> > [2019-11-04 11:54:08]  - Src/Unix_Log.py[Line:39] - INFO: 等待 6 分钟后打开宝箱
> > [2019-11-04 11:55:30]  - Src/Unix_Log.py[Line:39] - INFO: 向直播间  发送心跳包 (WEB)
> > [2019-11-04 11:55:31]  - Src/Unix_Log.py[Line:39] - INFO: 向直播间  发送心跳包 (APP)
> > [2019-11-04 11:55:51]  - Src/Unix_Log.py[Line:66] - CRITICAL: 房间 9905913 摩天大楼 抽奖结果: 辣条 X 1
> > 娱乐区广播：<%栗深林曦惊层巅%>投喂:<%栗子酱酱酱酱酱酱%>1个摩天大楼，点击前往TA的房间去抽奖吧
> > [2019-11-04 11:59:20]  - Src/Unix_Log.py[Line:66] - CRITICAL: 1 号弹幕监控检测到 2106735 的 1 个 摩天大楼
> > [2019-11-04 11:59:23]  - Src/Unix_Log.py[Line:39] - INFO: 抽奖脚本检测到房间 2106735 为正常房间
> > [2019-11-04 11:59:23]  - Src/Unix_Log.py[Line:39] - INFO: 本次获取到 摩天大楼 的抽奖id为: 463036
> > [2019-11-04 12:00:21]  - Src/Unix_Log.py[Line:39] - INFO: 参与了房间 2106735 的 摩天大楼 抽奖
> > [2019-11-04 12:00:21]  - Src/Unix_Log.py[Line:39] - INFO: 摩天大楼 抽奖状态: OK
> > ```
> 
> [2019-11-05 04:07:10,676] - Windows_Log.py[line:85] - CRITICAL: 3 号弹幕监控检测到 1186551 的 1 个 小电视飞船
> [2019-11-05 04:07:10,777] - Windows_Log.py[line:85] - CRITICAL: 2 号弹幕监控检测到 1186551 的 1 个 小电视飞船
> [2019-11-05 04:07:10,878] - Windows_Log.py[line:85] - CRITICAL: 1 号弹幕监控检测到 1186551 的 1 个 小电视飞船
> [2019-11-05 04:07:10,978] - Windows_Log.py[line:85] - CRITICAL: 5 号弹幕监控检测到 1186551 的 1 个 小电视飞船
> [2019-11-05 04:07:11,079] - Windows_Log.py[line:85] - CRITICAL: 4 号弹幕监控检测到 1186551 的 1 个 小电视飞船
> [2019-11-05 04:07:11,180] - Windows_Log.py[line:85] - CRITICAL: 6 号弹幕监控检测到 1186551 的 1 个 小电视飞船
> [2019-11-05 04:07:14,071] - Windows_Log.py[line:64] - INFO: 抽奖脚本检测到房间 1186551 为正常房间
> [2019-11-05 04:07:14,451] - Windows_Log.py[line:64] - INFO: 本次获取到 小电视飞船 的抽奖id为: 463516
> [2019-11-05 04:08:53,880] - Windows_Log.py[line:64] - INFO: 开始宝箱成功,获得 190 个银瓜子,当前有 169682 个银瓜子
> [2019-11-05 04:09:00,831] - Windows_Log.py[line:85] - CRITICAL: 6 号弹幕监控检测到 6154037 的 1 个 摩天大楼
> [2019-11-05 04:09:03,435] - Windows_Log.py[line:64] - INFO: 抽奖脚本检测到房间 6154037 为正常房间
> [2019-11-05 04:09:03,807] - Windows_Log.py[line:64] - INFO: 本次获取到 摩天大楼 的抽奖id为: 463517
> [2019-11-05 04:09:05,837] - Windows_Log.py[line:64] - INFO: 今天所有的宝箱已经领完!
> [2019-11-05 04:09:11,242] - Windows_Log.py[line:64] - INFO: 参与了房间 1186551 的 小电视飞船 抽奖
> [2019-11-05 04:09:11,343] - Windows_Log.py[line:64] - INFO: 小电视飞船 抽奖状态: 请升级APP版本
> [2019-11-05 04:09:44,844] - Windows_Log.py[line:64] - INFO: 向直播间 发送心跳包 (WEB)
> [2019-11-05 04:09:45,474] - Windows_Log.py[line:64] - INFO: 向直播间 发送心跳包 (APP)
> [2019-11-05 04:10:01,437] - Windows_Log.py[line:64] - INFO: 参与了房间 6154037 的 摩天大楼 抽奖
> [2019-11-05 04:10:01,538] - Windows_Log.py[line:64] - INFO: 摩天大楼 抽奖状态: 请升级APP版本
> [2019-11-05 04:14:45,802] - Windows_Log.py[line:64] - INFO: 向直播间 发送心跳包 (WEB)
> [2019-11-05 04:14:46,172] - Windows_Log.py[line:64] - INFO: 向直播间 发送心跳包 (APP)

本来想Release的,结果travis-ci的windows版本就是抽风了一直Build failed.我今天看一下有时间手动release下吧

**Comment by TheWanderingCoel** [comment]
> > > 最近同样被要求升级APP版本，我把最新更新的几个文件替换了一下还是有这个问题...
> > 
> > 
> > 我这里没有这个问题诶,能否麻烦下使用`git pull origin master`拉取最新文件一下看看?
> > 或者重新克隆一下这个项目?`git clone https://github.com/TheWanderingCoel/BiliBiliHelper.git`
> > ```
> > [2019-11-04 11:53:49]  - Src/Unix_Log.py[Line:66] - CRITICAL: 6 号弹幕监控检测到 21666995 的 舰长
> > [2019-11-04 11:53:51]  - Src/Unix_Log.py[Line:39] - INFO: 抽奖脚本检测到房间 21666995 为正常房间
> > [2019-11-04 11:53:51]  - Src/Unix_Log.py[Line:39] - INFO: 本次获取到的 大航海 抽奖id为 1628271
> > [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:39] - INFO: 参与了房间 21666995 的大航海抽奖
> > [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:66] - CRITICAL: 房间 21666995 大航海抽奖结果: 当前佩戴的粉丝勋章亲密度+1
> > [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:39] - INFO: 开始宝箱成功,获得 30 个银瓜子,当前有 4084 个银瓜子
> > [2019-11-04 11:54:08]  - Src/Unix_Log.py[Line:39] - INFO: 领取宝箱成功,内含 80 个瓜子
> > [2019-11-04 11:54:08]  - Src/Unix_Log.py[Line:39] - INFO: 等待 6 分钟后打开宝箱
> > [2019-11-04 11:55:30]  - Src/Unix_Log.py[Line:39] - INFO: 向直播间  发送心跳包 (WEB)
> > [2019-11-04 11:55:31]  - Src/Unix_Log.py[Line:39] - INFO: 向直播间  发送心跳包 (APP)
> > [2019-11-04 11:55:51]  - Src/Unix_Log.py[Line:66] - CRITICAL: 房间 9905913 摩天大楼 抽奖结果: 辣条 X 1
> > 娱乐区广播：<%栗深林曦惊层巅%>投喂:<%栗子酱酱酱酱酱酱%>1个摩天大楼，点击前往TA的房间去抽奖吧
> > [2019-11-04 11:59:20]  - Src/Unix_Log.py[Line:66] - CRITICAL: 1 号弹幕监控检测到 2106735 的 1 个 摩天大楼
> > [2019-11-04 11:59:23]  - Src/Unix_Log.py[Line:39] - INFO: 抽奖脚本检测到房间 2106735 为正常房间
> > [2019-11-04 11:59:23]  - Src/Unix_Log.py[Line:39] - INFO: 本次获取到 摩天大楼 的抽奖id为: 463036
> > [2019-11-04 12:00:21]  - Src/Unix_Log.py[Line:39] - INFO: 参与了房间 2106735 的 摩天大楼 抽奖
> > [2019-11-04 12:00:21]  - Src/Unix_Log.py[Line:39] - INFO: 摩天大楼 抽奖状态: OK
> > ```
> 
> 我把原来的文件删了重新指令了一遍还是这个问题...我用下载的bilibilihelper.exe打开提示要升级APP版本，直接用python main.py就是直接闪退和以下的错误
> $ python main.py
> Traceback (most recent call last):
> File "main.py", line 46, in
> Log.clean_log(startup=True)
> File "Src\Windows_Log.py", line 98, in clean_log
> open(os.getcwd()+"/Log/BiliBiliHelper.log", 'w').close()
> NameError: name 'os' is not defined
> 
> 以前都是可以打开main.py的现在突然闪退不行了...

我刚刚看了一下代码,突然发现``Windows_Log.py``里面漏了一个``import os``....我的大意,实在抱歉。马上push个commit修复下

**Comment by Peucha** [comment]
> > > > 最近同样被要求升级APP版本，我把最新更新的几个文件替换了一下还是有这个问题...
> > > 
> > > 
> > > 我这里没有这个问题诶,能否麻烦下使用`git pull origin master`拉取最新文件一下看看?
> > > 或者重新克隆一下这个项目?`git clone https://github.com/TheWanderingCoel/BiliBiliHelper.git`
> > > ```
> > > [2019-11-04 11:53:49]  - Src/Unix_Log.py[Line:66] - CRITICAL: 6 号弹幕监控检测到 21666995 的 舰长
> > > [2019-11-04 11:53:51]  - Src/Unix_Log.py[Line:39] - INFO: 抽奖脚本检测到房间 21666995 为正常房间
> > > [2019-11-04 11:53:51]  - Src/Unix_Log.py[Line:39] - INFO: 本次获取到的 大航海 抽奖id为 1628271
> > > [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:39] - INFO: 参与了房间 21666995 的大航海抽奖
> > > [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:66] - CRITICAL: 房间 21666995 大航海抽奖结果: 当前佩戴的粉丝勋章亲密度+1
> > > [2019-11-04 11:53:52]  - Src/Unix_Log.py[Line:39] - INFO: 开始宝箱成功,获得 30 个银瓜子,当前有 4084 个银瓜子
> > > [2019-11-04 11:54:08]  - Src/Unix_Log.py[Line:39] - INFO: 领取宝箱成功,内含 80 个瓜子
> > > [2019-11-04 11:54:08]  - Src/Unix_Log.py[Line:39] - INFO: 等待 6 分钟后打开宝箱
> > > [2019-11-04 11:55:30]  - Src/Unix_Log.py[Line:39] - INFO: 向直播间  发送心跳包 (WEB)
> > > [2019-11-04 11:55:31]  - Src/Unix_Log.py[Line:39] - INFO: 向直播间  发送心跳包 (APP)
> > > [2019-11-04 11:55:51]  - Src/Unix_Log.py[Line:66] - CRITICAL: 房间 9905913 摩天大楼 抽奖结果: 辣条 X 1
> > > 娱乐区广播：<%栗深林曦惊层巅%>投喂:<%栗子酱酱酱酱酱酱%>1个摩天大楼，点击前往TA的房间去抽奖吧
> > > [2019-11-04 11:59:20]  - Src/Unix_Log.py[Line:66] - CRITICAL: 1 号弹幕监控检测到 2106735 的 1 个 摩天大楼
> > > [2019-11-04 11:59:23]  - Src/Unix_Log.py[Line:39] - INFO: 抽奖脚本检测到房间 2106735 为正常房间
> > > [2019-11-04 11:59:23]  - Src/Unix_Log.py[Line:39] - INFO: 本次获取到 摩天大楼 的抽奖id为: 463036
> > > [2019-11-04 12:00:21]  - Src/Unix_Log.py[Line:39] - INFO: 参与了房间 2106735 的 摩天大楼 抽奖
> > > [2019-11-04 12:00:21]  - Src/Unix_Log.py[Line:39] - INFO: 摩天大楼 抽奖状态: OK
> > > ```
> > 
> > 
> > 我把原来的文件删了重新指令了一遍还是这个问题...我用下载的bilibilihelper.exe打开提示要升级APP版本，直接用python main.py就是直接闪退和以下的错误
> > $ python main.py
> > Traceback (most recent call last):
> > File "main.py", line 46, in
> > Log.clean_log(startup=True)
> > File "Src\Windows_Log.py", line 98, in clean_log
> > open(os.getcwd()+"/Log/BiliBiliHelper.log", 'w').close()
> > NameError: name 'os' is not defined
> > 以前都是可以打开main.py的现在突然闪退不行了...
> 
> 我刚刚看了一下代码,突然发现`Windows_Log.py`里面漏了一个`import os`....我的大意,实在抱歉。马上push个commit修复下

谢谢nasu
