### ISSUE TITLE
ERROR: 检测到无效的小电视类抽奖

### ISSUE THREAD

**Issue by luoshuijs** [TheWanderingCoel/BiliBiliHelper#31]
**介绍一下这个Bug**
logs输出
````
CRITICAL: 1 号弹幕监控检测到 XXXX 的 1 个 ‘木棍铲屎愁更愁’快去为主子抽口粮
CRITICAL: 抽奖脚本检测到房间 XXXX 为正常房间
ERROR: 检测到无效的小电视类抽奖
````
**系统环境 (请完成以下填入):**
 - 系统 [ubutun 19]
 - Python 版本 [3.6.5]

**额外信息**
初步判断弹幕监听的锅。

**Comment by luoshuijs** [comment]
好几个是这样
````
[2020-03-26 17:43:24,088] - CRITICAL: 1 号弹幕监控检测到 11301073 的 1 个 小电视地图历险
[2020-03-26 17:43:26,438] - CRITICAL: 抽奖脚本检测到房间 11301073 为正常房间
[2020-03-26 17:43:26,745] - ERROR: 检测到无效的小电视类抽奖
````
估计这类应该走的是大航海请求，而不是小电视,DokiDoki,摩天大楼之类的请求。
目前看了一下弹幕监控看到我头都秃了。、
目前解决方法就两个：
1、修改弹幕监听，重新加强分类
2、如果

**Comment by TheWanderingCoel** [comment]
这个算tv类的，然后他它data的返回值是Null，我就直接让他error了。最近都没空修哎

**Comment by luoshuijs** [comment]
> 这个算tv类的，然后他它data的返回值是Null，我就直接让他error了。最近都没空修哎

然而我刚刚发现这类请求却是调用大航海的Check。很迷.....
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/c2776650aaf48aefa8c082889fff83a39d703e07/Src/BasicRequest.py#L67-L71
后面也最后调用了大航海的join。

**Comment by luoshuijs** [comment]
是的，返回值就是Null。讲道理，如果是Null他怎么去检查呢。
当时我就找到了这个房间号去调试，发现请求中就只有大航海请求返回了正确数据，其他都是Null。

**Comment by TheWanderingCoel** [comment]
B站迷惑行为大赏，在弹幕监听里是tv类的

**Comment by luoshuijs** [comment]
> B站迷惑行为大赏，在弹幕监听里是tv类的

是的，刚刚以防万一我搞错了再去试了一下，发现真生草。过程说明一下。
看到日记错误时候立即打开了直播间
````
[2020-03-26 18:11:12,129] - CRITICAL: 3 号弹幕监控检测到 XXX 的 1 个 ‘木棍铲屎愁更愁’快去为主子抽口粮
[2020-03-26 18:11:14,452] - CRITICAL: 抽奖脚本检测到房间 XXX 为正常房间
[2020-03-26 18:11:14,782] - ERROR: 检测到无效的小电视类抽奖
````
搜索全部Check。就发现只有大航海的Check返回了数据。
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/81178587f4b83e459bfa8c0fdb21b7c023775506/Src/BasicRequest.py#L70
有意思的是数据在data→gift。
下面是返回的数据。
````
{
    "code": 0,
    "message": "0",
    "ttl": 1,
    "data": {
        "pk": [],
        "guard": [],
        "gift": [
            {
                "raffleId": XXX,
                "type": "GIFT_0",
                "from_user": {
                    "uid": 0,
                    "uname": "XXX",
                    "face": "XXXX"
                },
                "time_wait": 83,
                "time": 143,
                "max_time": 180,
                "status": 1,
                "sender_type": 0,
                "asset_icon": "https://i0.hdslb.com/bfs/live/a5592e79441f26c197e4a7a141bf96e28ebb5c66.png",
                "asset_animation_pic": "https://i0.hdslb.com/bfs/live/471896e207029b9346b7fe79e33e6de1d24a49e1.gif",
                "thank_text": "感谢<%XXXXX%> 赠送的充能",
                "weight": 0,
                "gift_id": 0
            }
        ]
    }
}
````
时间到点击获取，调用的也是大航海的join
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/81178587f4b83e459bfa8c0fdb21b7c023775506/Src/BasicRequest.py#L76
调用方法基本一样，返回也是。
突然生草了起来。

**Comment by TheWanderingCoel** [comment]
草，生了出来。B站太屑了，我看看怎么才能handle

**Comment by luoshuijs** [comment]
如果真的弹幕监听里是tv类的，真的只能从那边Tv类的请求中再添加个判断了（if checklen == Null），检查是否是其他Check是否存在了。类似B站进入直播见后都会吧4个Check调用。
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/81178587f4b83e459bfa8c0fdb21b7c023775506/Src/Tv_Raffle_Handler.py#L28-L42

**Comment by TheWanderingCoel** [comment]
> 如果真的弹幕监听里是tv类的，真的只能从那边Tv类的请求中再添加个判断了（if checklen == Null），检查是否是其他Check是否存在了。类似B站进入直播见后都会吧4个Check调用。
> https://github.com/TheWanderingCoel/BiliBiliHelper/blob/81178587f4b83e459bfa8c0fdb21b7c023775506/Src/Tv_Raffle_Handler.py#L28-L42

确实，我也这么想的，也只能这样了，真是服了B站

**Comment by luoshuijs** [comment]
我觉得还是弹幕监控这边问题，毕竟输出很奇怪什么鬼的`‘木棍铲屎愁更愁’快去为主子抽口粮`。
刚刚这边也输出一些奇怪的东西
````
[2020-03-26 18:30:06,203] - CRITICAL: 5 号弹幕监控检测到 XX 的 1 个
[2020-03-26 18:30:08,532] - CRITICAL: 抽奖脚本检测到房间 XXX 为正常房间
[2020-03-26 18:30:08,828] - ERROR: 检测到无效的小电视类抽奖
````
就`检测到 XX 的 1 个` ，后面是一个什么都不知道。
还有那个`没猫铲屎有点愁`的奖品我在B站直播看到的是`感谢XXXX赠送的充能`，估计这很迷惑了。

**Comment by TheWanderingCoel** [comment]
这也太迷惑了，我有空看下吧，感谢反馈

**Comment by luoshuijs** [comment]
刚刚看了隔壁的项目，这种礼物应该是属于[广播道具抽奖](https://github.com/Dawnnnnnn/bilibili-live-tools/blob/38a71caf3f350753b933268065a5171cddca2209/bilibiliCilent.py#L37)类。其中正好对应[返回](https://github.com/TheWanderingCoel/BiliBiliHelper/issues/31#issuecomment-604347172)的数据[data→gift](https://github.com/Dawnnnnnn/bilibili-live-tools/blob/38a71caf3f350753b933268065a5171cddca2209/bilibiliCilent.py#L51)。用的接口完全和大航海一样。估计还得又得折磨了......
如果弹幕监听不了用最好还是挂[服务器](https://github.com/Billyzou0741326/bilibili-live-monitor-js)监听，毕竟这效率才是最大的。
提个意见，在服务器可用的情况关闭弹幕监控，毕竟有时候真不如服务器监控。
服务器这边也是能监控广播道具（对应里面的GIFT_20003（后面数字是礼物类型））抽奖这类的。
````
0|live  |  [2020-03-26 19:23:34]   778159       @21618129     GIFT_20003   摩天大楼抽奖
0|live  |  [2020-03-26 19:23:52]   871882       @5101555      pk           大乱斗
0|live  |  [2020-03-26 19:23:55]   2252625      @15152878     storm        节奏风暴         2252625113348
0|live  |  [2020-03-26 19:23:56]   2252626      @1156962      guard        舰长
0|live  |  [2020-03-26 19:24:01]   2252627      @528833       guard        舰长
0|live  |  [2020-03-26 19:24:04]   2252628      @21013446     guard        舰长
0|live  |  [2020-03-26 19:24:09]   2252629      @21403609     guard        舰长
0|live  |  [2020-03-26 19:24:16]   2252630      @289079       storm        节奏风暴         2252630448534
0|live  |  [2020-03-26 19:24:29]   871884       @21291018     pk           大乱斗
0|live  |  [2020-03-26 19:24:42]   871887       @21999134     pk           大乱斗
0|live  |  [2020-03-26 19:24:47]   2252631      @6763657      guard        舰长
0|live  |  [2020-03-26 19:24:53]   871938       @21945916     pk           大乱斗
0|live  |  [2020-03-26 19:24:56]   2252632      @15122867     guard        舰长
0|live  |  [2020-03-26 19:24:58]   2252633      @514278       guard        舰长
0|live  |  [2020-03-26 19:25:02]   2252634      @15152878     guard        舰长
0|live  |  [2020-03-26 19:25:21]   2252635      @15152878     guard        舰长
0|live  |  [2020-03-26 19:25:24]   871889       @10036668     pk           大乱斗
0|live  |  [2020-03-26 19:25:29]   2252636      @21180272     guard        舰长
0|live  |  [2020-03-26 19:25:30]   2252637      @21981066     storm        节奏风暴         2252637164414
0|live  |  [2020-03-26 19:25:32]   2252638      @1253090      guard        舰长
0|live  |  [2020-03-26 19:25:38]   871890       @21773215     pk           大乱斗
0|live  |  [2020-03-26 19:25:41]   Monitoring (静态) 6561 + (动态) 16729
0|live  |  [2020-03-26 19:25:44]   2252639      @1507681      guard        舰长
0|live  |  [2020-03-26 19:25:50]   2252640      @21890658     guard        舰长
0|live  |  [2020-03-26 19:25:50]   1019740      @21954922     GIFT_30405   33地图抽奖抽奖
0|live  |  [2020-03-26 19:25:51]   1019741      @1361615      GIFT_30405   33地图抽奖抽奖
0|live  |  [2020-03-26 19:25:51]   1019742      @10797503     GIFT_30405   33地图抽奖抽奖
0|live  |  [2020-03-26 19:25:58]   2252641      @21694730     guard        舰长
````
在下面这部分修改一下（注释掉了可还行）
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/c2776650aaf48aefa8c082889fff83a39d703e07/Src/Monitor_Server.py#L159-L167
毕竟弹幕监控和服务器最好用其中一个就行了，毕竟如果两个都兼顾可想而知后期维护也会越来越麻烦。
所以说没有服务器用弹幕监控，有服务器最好就用服务器。

**Comment by TheWanderingCoel** [comment]
> 刚刚看了隔壁的项目，这种礼物应该是属于[广播道具抽奖](https://github.com/Dawnnnnnn/bilibili-live-tools/blob/38a71caf3f350753b933268065a5171cddca2209/bilibiliCilent.py#L37)类。其中正好对应[返回](https://github.com/TheWanderingCoel/BiliBiliHelper/issues/31#issuecomment-604347172)的数据[data→gift](https://github.com/Dawnnnnnn/bilibili-live-tools/blob/38a71caf3f350753b933268065a5171cddca2209/bilibiliCilent.py#L51)。用的接口完全和大航海一样。估计还得又得折磨了......
> 如果弹幕监听不了用最好还是挂[服务器](https://github.com/Billyzou0741326/bilibili-live-monitor-js)监听，毕竟这效率才是最大的。
> 提个意见，在服务器可用的情况关闭弹幕监控，毕竟有时候真不如服务器监控。
> 服务器这边也是能监控广播道具（对应里面的GIFT_20003（后面数字是礼物类型））抽奖这类的。
> 
> ```
> 0|live  |  [2020-03-26 19:23:34]   778159       @21618129     GIFT_20003   摩天大楼抽奖
> 0|live  |  [2020-03-26 19:23:52]   871882       @5101555      pk           大乱斗
> 0|live  |  [2020-03-26 19:23:55]   2252625      @15152878     storm        节奏风暴         2252625113348
> 0|live  |  [2020-03-26 19:23:56]   2252626      @1156962      guard        舰长
> 0|live  |  [2020-03-26 19:24:01]   2252627      @528833       guard        舰长
> 0|live  |  [2020-03-26 19:24:04]   2252628      @21013446     guard        舰长
> 0|live  |  [2020-03-26 19:24:09]   2252629      @21403609     guard        舰长
> 0|live  |  [2020-03-26 19:24:16]   2252630      @289079       storm        节奏风暴         2252630448534
> 0|live  |  [2020-03-26 19:24:29]   871884       @21291018     pk           大乱斗
> 0|live  |  [2020-03-26 19:24:42]   871887       @21999134     pk           大乱斗
> 0|live  |  [2020-03-26 19:24:47]   2252631      @6763657      guard        舰长
> 0|live  |  [2020-03-26 19:24:53]   871938       @21945916     pk           大乱斗
> 0|live  |  [2020-03-26 19:24:56]   2252632      @15122867     guard        舰长
> 0|live  |  [2020-03-26 19:24:58]   2252633      @514278       guard        舰长
> 0|live  |  [2020-03-26 19:25:02]   2252634      @15152878     guard        舰长
> 0|live  |  [2020-03-26 19:25:21]   2252635      @15152878     guard        舰长
> 0|live  |  [2020-03-26 19:25:24]   871889       @10036668     pk           大乱斗
> 0|live  |  [2020-03-26 19:25:29]   2252636      @21180272     guard        舰长
> 0|live  |  [2020-03-26 19:25:30]   2252637      @21981066     storm        节奏风暴         2252637164414
> 0|live  |  [2020-03-26 19:25:32]   2252638      @1253090      guard        舰长
> 0|live  |  [2020-03-26 19:25:38]   871890       @21773215     pk           大乱斗
> 0|live  |  [2020-03-26 19:25:41]   Monitoring (静态) 6561 + (动态) 16729
> 0|live  |  [2020-03-26 19:25:44]   2252639      @1507681      guard        舰长
> 0|live  |  [2020-03-26 19:25:50]   2252640      @21890658     guard        舰长
> 0|live  |  [2020-03-26 19:25:50]   1019740      @21954922     GIFT_30405   33地图抽奖抽奖
> 0|live  |  [2020-03-26 19:25:51]   1019741      @1361615      GIFT_30405   33地图抽奖抽奖
> 0|live  |  [2020-03-26 19:25:51]   1019742      @10797503     GIFT_30405   33地图抽奖抽奖
> 0|live  |  [2020-03-26 19:25:58]   2252641      @21694730     guard        舰长
> ```
> 
> 在下面这部分修改一下（注释掉了可还行）
> https://github.com/TheWanderingCoel/BiliBiliHelper/blob/c2776650aaf48aefa8c082889fff83a39d703e07/Src/Monitor_Server.py#L159-L167
> 
> 
> 毕竟弹幕监控和服务器最好用其中一个就行了，毕竟如果两个都兼顾可想而知后期维护也会越来越麻烦。
> 所以说没有服务器用弹幕监控，有服务器最好就用服务器。

嗯嗯，谢谢大佬了

**Comment by luoshuijs** [comment]
大佬也辛苦了，估计后面得潜水一阵子专心学习了，谢谢你！

**Comment by TheWanderingCoel** [comment]
> 大佬也辛苦了，估计后面得潜水一阵子专心学习了，谢谢你！

我也咕咕咕了，好久没维护了

**Comment by Billyzou0741326** [comment]
嗯... 总结一下
pk gift guard 的check全部来自这个API
`https://api.live.bilibili.com/xlive/lottery-interface/v1/lottery/Check?roomid=`

这三个合并一下就差不多了吧
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/c2776650aaf48aefa8c082889fff83a39d703e07/Src/BasicRequest.py#L21-L22
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/c2776650aaf48aefa8c082889fff83a39d703e07/Src/BasicRequest.py#L49-L50
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/c2776650aaf48aefa8c082889fff83a39d703e07/Src/BasicRequest.py#L69-L70
