### ISSUE TITLE
诡异的的抽奖统计

### ISSUE THREAD

**Issue by luoshuijs** [TheWanderingCoel/BiliBiliHelper#33]
**介绍一下这个Bug**
如下，省略2000字。

**额外信息**
输入查询本次推送抽奖统计命令（1）
````
1
本次推送抽奖统计:
3575  X 应援喵
 104  X 摩天大楼
 66   X 全区任意门
 19   X 分区任意门
 76   X 终极任务‘人在家中坐
 44   X 一只猫
 65   X ‘没猫铲屎有点愁’
 54   X 1219蘑菇方舟
 47   X ‘木棍铲屎愁更愁’快去为主子抽口粮
 234  X 白羊座流星雨
 114  X ‘撸猫撸到手发油’
 381  X 小电视飞船
 46   X 小电视地图历险
  7   X 开播
  3   X 33地图历险
  5   X

本次参与抽奖统计：
 831  X 小电视类(合计)

本次抽奖结果统计：
1391  X 辣条
````
有几个名称很奇怪，最后一个5X后面跟着都不知道是什么，更诡异的是居然礼物还有一个叫开播的玩意¿

**Comment by luoshuijs** [comment]
专业挖掘BUG小助手.jpg
初步调试推测还是鬼才弹幕监控惹得锅。

**Comment by luoshuijs** [comment]
和之前已经关闭的问题一个样子,最早在Check礼物的时候的输出异常，<del>奇怪的输出增加了
</del>https://github.com/TheWanderingCoel/BiliBiliHelper/issues/31#issuecomment-604354457
如果用之前大佬的那个监控服务器推测这类还估计是这些是应援喵抽奖
````
0|live  |  [2020-03-27 00:43:31]   779192       @5438584      GIFT_30277   应援喵抽奖
0|live  |  [2020-03-27 00:43:50]   2255428      @13570680     storm        节奏风暴         2255428849449
0|live  |  [2020-03-27 00:44:00]   779193       @284560       GIFT_30277   应援喵抽奖
````

**Comment by Billyzou0741326** [comment]
好吧 找找看那些喵是从哪钻出来的...

**Comment by Billyzou0741326** [comment]
最后找到了这里
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/84525472a347f70fdedf932a7038d398ec6c0945/Src/Danmu.py#L227-L243

解析string判定礼物类别确实不太稳 推送方面的统计来自弹幕`NOTICE_MSG` 只能从那行奇怪的message入手2333
如果改接Server的推送（现在是无视小电视类推送）就比较方便了 不过程序是默认在无服务器状态下也可以运行的 所以弹幕监控放弃解析礼物名一并归入`小电视类`好了

**Comment by Billyzou0741326** [comment]
比如 `msg_common: "主播<%栗子酱酱酱酱酱酱%>完成了终极任务‘人在家中坐，猫从天上来’，终极大奖先到先得~"`
这种会统计成很神奇的礼物名 果然是`76   X 终极任务‘人在家中坐`...
