### ISSUE TITLE
开启硬币换银瓜子时出现Python协程报错

### ISSUE THREAD

**Issue by luoshuijs** [TheWanderingCoel/BiliBiliHelper#35]
**介绍一下这个Bug**
开启硬币换银瓜子时出现错误（只要开启就会出现）
````
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xffff9b0cd390>
````
没有往下测试，毕竟银瓜子不足。
````
[2020-03-27 04:23:18] [WARNING] 银瓜子余额不足
````
不知道影响还是不影响换瓜子的流程。
刚刚给小号绑定手机，估计得等一下。

**Comment by luoshuijs** [comment]
估计是这里，异常类型为`request_json() got an unexpected keyword argument 'sign'`
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/f24b93e864cc44374a2a441c329362749894bd6b/Src/Coin2Silver.py#L36
发现在定义根本没有`sign`这种变量
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/8bd7cb2a2b3f691ee457cc5a6f52bf6647b518a6/Src/AsyncioCurl.py#L45-L72

**Comment by luoshuijs** [comment]
删掉即可√

**Comment by Billyzou0741326** [comment]
嗯 sign是给手机端请求用的 奇怪的是只有Curl的同步request才有... 
pr一个吧 我得肝课本了...

**Comment by luoshuijs** [comment]
> 嗯 sign是给手机端请求用的 奇怪的是只有Curl的同步request才有...
> pr一个吧 我得肝课本了...

我先睡个觉，等等再推送请求。

**Comment by Billyzou0741326** [comment]
好吧好吧 别被我抢先了啊hhh

**Comment by luoshuijs** [comment]
> 好吧好吧 别被我抢先了啊hhh

哈哈哈都一样）

**Comment by luoshuijs** [comment]
提交再睡2333）
