### ISSUE TITLE
每日礼包功能问题

### ISSUE THREAD

**Issue by luoshuijs** [TheWanderingCoel/BiliBiliHelper#41]
这是谁写的代码，出来挨打.py
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/31871364da676798f1183fa60c77080698855ff7/Src/DailyBag.py#L31

**Comment by TheWanderingCoel** [comment]
我（

**Comment by luoshuijs** [comment]
惊了，居然这还Build Passed过了（震撼狗妈）

**Comment by luoshuijs** [comment]
难道不是这样写吗
 `if len(self.done) >= 2: `
奇怪的知识增加了.jpg

**Comment by TheWanderingCoel** [comment]
诶我记得我不是这样写的hhh 不论怎样都能passed的hhh

**Comment by luoshuijs** [comment]
居然也没日记输出，太迷惑了。
刚刚这边我调了最高级别异常捕获，然后突然引发了异常，不然一辈子都不知道这里有个迷惑玩意。

**Comment by luoshuijs** [comment]
复制详细信息
```
  Message='>=' not supported between instances of 'list' and 'int'
  Source=H:\BiliBiliHelper\Src\DailyBag.py
  StackTrace:
  File "H:\BiliBiliHelper\Src\DailyBag.py", line 31, in work
    if len(self.done >= 2):
  File "H:\BiliBiliHelper\main.py", line 125, in <module>
    loop.run_until_complete(asyncio.wait(daily_tasks+server_tasks+danmu_tasks+other_tasks))
```

**Comment by TheWanderingCoel** [comment]
async经典有错误都不输出的hhh,话说怎么调最高级别hhhh。我也才发现写成了这个鬼东西，感谢感谢，我的锅

**Comment by luoshuijs** [comment]
这玩意调试才有：异常设置这边，Python Exceptions下面的选项全部打钩了
我就纳闷了如果这种错误都应该有输出才对，结果就只是停止运行了
太迷惑了

**Comment by TheWanderingCoel** [comment]
async是这样的

**Comment by luoshuijs** [comment]
行吧，怪不得我注意到礼包老是是没有领取的，原来问题出现在这里，可以。
刚刚弄自动送礼的问题突然出现这个异常，我当时差点不理hhh

**Comment by TheWanderingCoel** [comment]
抱歉抱歉，我的锅

**Comment by luoshuijs** [comment]
> 抱歉抱歉，我的锅

哈哈哈只是调侃一下，我觉得过几个月还真没人知道呢

**Comment by TheWanderingCoel** [comment]
> 哈哈哈只是调侃一下，我觉得过几个月还真没人知道呢

hhh确实，他没报错我也没管过
