### ISSUE TITLE
弹幕监控和服务器监控重复请求

### ISSUE THREAD

**Issue by luoshuijs** [TheWanderingCoel/BiliBiliHelper#44]
**介绍一下这个Bug**
估计刚刚弹幕监控和服务器监控返回了一样的数据，结果触发了402错误
突然大量请求，简直就是CC攻击啊。
从日记里面的礼物ID看出是重复获取了，当时突然出现了一堆礼物。
结果弹幕监控和服务器监控同时收到一起Push进了任务领取队列里面，结果导致重复领取+触发402。
```
[2020-03-28 12:30:17] [RAFFLE] 本次获取到 终极任务‘人在家中坐 的抽奖id为: 1022485
[2020-03-28 12:30:17] [RAFFLE] 本次获取到 应援喵 的抽奖id为: 1022485
```
今晚土豪真多.5亿金瓜子....啧啧啧

**Comment by luoshuijs** [comment]
论如何用钱触发带CC攻击.jpg

**Comment by TheWanderingCoel** [comment]
我不是故意CC的（误，我之前push了一个commit, 监控服务器和弹幕只能选一个

**Comment by luoshuijs** [comment]
顺便估计这里前面加个随机sleep，<del>毕竟我们是来白嫖的不算打别人服务器的</del>
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/d36bc21af74b7c8fb8ccc8b4f0d24ef4fd3f5a46/Src/Tv_Raffle_Handler.py#L52

**Comment by TheWanderingCoel** [comment]
自己搭建服务器不香嘛，墙裂推荐 @Billyzou0741326 的监控服务器

**Comment by luoshuijs** [comment]
> 自己搭建服务器不香嘛，墙裂推荐 @Billyzou0741326 的监控服务器

我现在就是用着大佬搭建的啊，不然弹幕监控和服务器监控同时收到

**Comment by luoshuijs** [comment]
> 我不是故意CC的（误，我之前push了一个commit, 监控服务器和弹幕只能选一个

那就奇怪了，怎么回事.jpg

**Comment by TheWanderingCoel** [comment]
大佬你看看我那个commit，新加了个perfer_Server的参数，这两个不会同时运行了

**Comment by luoshuijs** [comment]
行我看看

**Comment by luoshuijs** [comment]
> 今天21773215这个房间爆炸了，建议各位做好提前休眠准备，我这边刷了一大堆系统繁忙稍等5s
> 
> 这个房间的辣条量我算了一下应该能有1K了

https://github.com/Dawnnnnnn/bilibili-live-tools/issues/22#issuecomment-605445733

真的牛逼

**Comment by TheWanderingCoel** [comment]
我收到Notification了，大佬使用金钱让挂机脚本发起了CC攻击（不是

**Comment by luoshuijs** [comment]
行，是我这边问题，那这样了hhh
