### ISSUE TITLE
自动送礼又……出事了

### ISSUE THREAD

**Issue by luoshuijs** [TheWanderingCoel/BiliBiliHelper#46]
**介绍一下这个Bug**
刚刚写完作业喵了一眼。
淦，在亲密度满的情况下还送出礼物了。
2000包辣条自动泡汤。<del>(还好是是朋友的号)</del>
配置一个房间就没出现这问题，两个就出事了。
奇怪.jpg

**Comment by TheWanderingCoel** [comment]
当初写的时候并没有计算剩余今日亲密度，~~因为懒~~。所以就全送出去了

**Comment by luoshuijs** [comment]
估计这个项目隔差三五就出事，估计维护很吃力啊……
<del>(毕竟2个月前大佬都咕咕咕也不奇怪，留着一堆吃灰bug)</del>
再过几天要回校高考了(哭唧唧)

**Comment by luoshuijs** [comment]
@TheWanderingCoel 但是你写了一个请求来判断亲密度是否满了，所以说我觉得很奇怪是为什么……

**Comment by luoshuijs** [comment]
估计是逻辑问题

**Comment by TheWanderingCoel** [comment]
> @TheWanderingCoel 但是你写了一个请求来判断亲密度是否满了，所以说我觉得很奇怪是为什么……

没写好，写一半就给我扔了，咕咕咕了好几个月没在维护这个项目。我脚本也没开着

**Comment by luoshuijs** [comment]
23333大佬你高兴就行了。明天我再看看怎么回事，估计10分钟就能搞定(毕竟得上网课，抽个课余时间)

**Comment by TheWanderingCoel** [comment]
大佬有tg么，加个一起咕咕咕2333

**Comment by luoshuijs** [comment]
> 大佬有tg么，加个一起咕咕咕2333

连接我发到你主页的那个邮箱可以不

**Comment by luoshuijs** [comment]
@TheWanderingCoel https://t.me/luoshuijs

**Comment by TheWanderingCoel** [comment]
确实…咕咕咕！话说大佬有tg么，加一个2333

**Comment by luoshuijs** [comment]
#48

**Comment by luoshuijs** [comment]
昨天学校宿舍晚睡觉时候，都™快睡着了，突然惊醒。脑子灵光一闪。
草。发现这破玩意，根本没有解决问题。
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/e409d2f0b8659e94ef306913921bb0d4bdfb343c/Src/GiftSend.py#L53-L55
莫得感情，懒得脑内编程，继续睡觉了。
（在学校莫得TG用（笑），而且带隔离）

**Comment by Billyzou0741326** [comment]
没事 我们也都忙得咕掉了
