### ISSUE TITLE
抛出解码异常

### ISSUE THREAD

**Issue by Yodamt** [TheWanderingCoel/BiliBiliHelper#49]
Task exception was never retrieved
future: <Task finished name='Task-182' coro=<BaseDanmu.read_datas() done, defined at /storage/emulated/0/BiliBiliHelper-master/Src/Danmu.py:110> exception=UnicodeDecodeError('utf-8', b'x\xdaD\xce\xbfJ\x03A\x10\x06\xf0\xb3\xd0\xdag\xf8\xea\xaf\x98\xfd3\xbb{\xd7)\x11\xab\xd8\x88\xd5z\x08\x9e\nB\x8c\x85I\x15R\xa8\x95\x85`#6\xda\xdaX\xf9\x00\xf1m\xce\xf8\x18\xb2!\x90\x19\xf8\x9a\xf9\r3U\xb5\xb5S\xedV\xa5\xb6K\xcc\xd0\xdd\\\xa0\xc1`\xefhxr6<>\x04q=\xbe\xbaE\x93\xb3\xd0\xd0*M\x881Z\xa34\x9a\x82J\xac\xc5\x8b\x0ft\xdezo\xd4\x19\nq.\xdeZ\xd5\x0e\x94\xd2-\xf1\xfb\xfe\xb4\xbc\xff\xea\x17\xdf\x7f\x0f\x1f\xfd\xcb\x1b\x98m\x12\tI|"\xfa\xe7\xc7\xe5\xcf\xa2\x7f\xfd\\{\x1a\x11)\xe7\x80\x96\xb9ev\x14\xd6)\xa4Z\x858\x9d\x8a\xb8K-\xa4\x8c\x81\x15+k\xe3\xe9h\xc4\x19&wh6\xcf\x11\xdd\x04\r\xd2At\xde\xed\x0f0\xdf\xd0UH;\xff\x0f\x00\x00\xff\xff\x88\xc6E$', 1, 2, 'invalid continuation byte')>
Traceback (most recent call last):
  File "/storage/emulated/0/BiliBiliHelper-master/Src/Danmu.py", line 134, in read_datas
    if not self.handle_danmu(body):
  File "/storage/emulated/0/BiliBiliHelper-master/Src/Danmu.py", line 204, in handle_danmu
    data = json.loads(body.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 1: invalid continuation byte

已经尝试过12退出，下次进入依然会抛出异常

**Comment by Yodamt** [comment]
网络环境是稳定的，安卓9 python3.8.2 termux运行
![QQ图片20200410164508](https://user-images.githubusercontent.com/15728632/78977437-ba342f80-7b4a-11ea-9980-5cf6b4392677.jpg)

**Comment by Billyzou0741326** [comment]
b站问题

**Comment by Billyzou0741326** [comment]
还在复现吗 如果持续出错的话 我找时间修一下

**Comment by Yodamt** [comment]
> 还在复现吗 如果持续出错的话 我找时间修一下

还在复现 每次都是0xda解码异常

**Comment by luoshuijs** [comment]
用大佬你的tools能解决100%问题（雾）------------------ 原始邮件 ------------------
发件人: "kotoriのねこ"<notifications@github.com>
发送时间: 2020年4月10日(星期五) 下午5:11
收件人: "TheWanderingCoel/BiliBiliHelper"<BiliBiliHelper@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [TheWanderingCoel/BiliBiliHelper] 抛出解码异常 (#49)




 
还在复现吗 如果持续出错的话 我找时间修一下
 
&mdash;

**Comment by Billyzou0741326** [comment]
我的才不解决问题呢233

protover更换成2了 我晚点改下封装解压方法和handshake 没时间了现在

**Comment by luoshuijs** [comment]
python的编码问题一直都很头疼.jpg

**Comment by luoshuijs** [comment]
我也没空，今天模拟炸了。（哭死）

**Comment by TheWanderingCoel** [comment]
我家里有点事，基本上几年都不会有空了...

**Comment by EdrowsLuo** [comment]
貌似b站的ws的格式改成二进制了，还没有找到解码的方式，不知道以前是明文传播还是说和现在一样的是一串二进制数据

**Comment by Billyzou0741326** [comment]
@TheWanderingCoel coel大佬不用折腾项目了 我这边见缝插针地划水就好了
@EdrowsLuo ws格式基本 protover升级而已 压缩方式小修改

**Comment by Yodamt** [comment]
> @TheWanderingCoel coel大佬不用折腾项目了 我这边见缝插针地划水就好了
> @EdrowsLuo ws格式基本没变 protover升级而已 压缩方式小修改

强啊23333佬

**Comment by Billyzou0741326** [comment]
没有 老鸽子了）
