### ISSUE TITLE
[Enhancement] aiohttp.WS

### ISSUE THREAD

**Issue by Billyzou0741326** [TheWanderingCoel/BiliBiliHelper#5]
看了下aiohttp的[ws文档](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.ws_connect)，client是有自动对ping的pong反馈

所以这里可以不用asyncio.wait的timeout
https://github.com/TheWanderingCoel/BiliBiliHelper/blob/01059eb99c8cdd4c5429be2009329fb5ce30948d/Src/Monitor_Server.py#L91

写了个demo
```python
import asyncio
import aiohttp
import json


async def main():
    session = aiohttp.ClientSession()
    ws = await session.ws_connect(
            'ws://127.0.0.1:8999')

    while True:
        msg = await ws.receive()

        if msg.type == aiohttp.WSMsgType.binary:
            print('Binary', msg.data)
            text = msg.data.decode('utf-8')
            data = json.loads(text)
            print(data)
        elif msg.type == aiohttp.WSMsgType.text:
            # Impossible
            pass
        elif msg.type == aiohttp.WSMsgType.closed:
            print('Closed')
            break
        elif msg.type == aiohttp.WSMsgType.error:
            print('Errored')
            break

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

测试后得出的结论是 服务端掉线（强制停止）的时候会触发`msg.type == aiohttp.WSMsgType.closed` 可以通过这个判定服务端掉线

**Comment by TheWanderingCoel** [comment]
好的👌,十分感谢大佬，麻烦了

**Comment by Billyzou0741326** [comment]
大佬过奖了

这规模的client已经比我强了hhh

**Comment by TheWanderingCoel** [comment]
有一部分参照了``bilibili-live-tools``的那个``danmu.py`` hhh.

**Comment by Billyzou0741326** [comment]
那个服务器的出处就比较恐怖了23333

风纪委的功能也可以考虑写进去（如果有时间肝的话hhh）
无论如何已经可以取代我的client了

**Comment by TheWanderingCoel** [comment]
> 那个服务器的出处就比较恐怖了23333
> 
> 风纪委的功能也可以考虑写进去（如果有时间肝的话hhh）
> 无论如何已经可以取代我的client了

大佬过奖hhh  主要是看到大佬wiki增加了风纪委员的接口,我就写了风纪委员的功能
其实我也想把那个动态抽奖写进去的2333，目前没啥好思路...

**Comment by Billyzou0741326** [comment]
诶 我没玩过动态抽奖 所以也不知道怎么抓.....

**Comment by TheWanderingCoel** [comment]
没事没事,慢慢来,大佬的wiki已经很丰富了

**Comment by TheWanderingCoel** [comment]
已完成,先关了23333

**Comment by Billyzou0741326** [comment]
好快速~

**Comment by TheWanderingCoel** [comment]
> 好快速~

因为实在是没啥事情可以干hhh

**Comment by Billyzou0741326** [comment]
> 因为实在是没啥事情可以干hhh

羡慕死了 我想法不少但时间没有2333

**Comment by TheWanderingCoel** [comment]
> > 因为实在是没啥事情可以干hhh
> 
> 羡慕死了 我想法不少但时间没有2333

太惨了，可怜下大佬
