### ISSUE TITLE
systemd 脚本

### ISSUE THREAD

**Issue by youaremywind** [TheWanderingCoel/BiliBiliHelper#6]
systemd 脚本 报错
<img width="581" alt="Screen Shot 2020-01-21 at 3 44 08 PM" src="https://user-images.githubusercontent.com/18423358/72785034-2f3b4b80-3c65-11ea-9f26-d82f1e17a27c.png">

**Comment by TheWanderingCoel** [comment]
看样子是因为路径的问题没有正确导入Console模块,让我测试下。

**Comment by TheWanderingCoel** [comment]
可以暂时使用screen代替systemd, 正在想办法修复

**Comment by TheWanderingCoel** [comment]
应该修复了,有问题欢迎随时reopen这个issue
