### ISSUE TITLE
移植到路由器上的可能性

### ISSUE THREAD

**Issue by lhllhx** [TheWanderingCoel/BiliBiliHelper#61]
最近在弄openwrt 有没有可能把二进制文件移植到路由器上（整个python移植文件太大了），但是好像因为路由器是arm处理器所以移植有一定难度！？
如果能在路由器上跑就太爽了！

**Comment by EdrowsLuo** [comment]
python又不是编译成二进制码，你得看你的处理器有没有python运行时，有了这些库也不一定支持

**Comment by lhllhx** [comment]
找到曲线救国的方法 但现在特殊时期不好透露，等避完风头再说
