### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by 2438175594** [TheWanderingCoel/BiliBiliHelper#7]
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import Console
ModuleNotFoundError: No module named 'Console'
![Screenshot_2020-01-21-19-54-48-79](https://user-images.githubusercontent.com/46627115/72803041-155f3000-3c88-11ea-91aa-af46f99cfc08.png)

**Comment by TheWanderingCoel** [comment]
``main.py``一个粗心大小写错了，麻烦重新``git pull``一下,问题应该已经修复。
