### ISSUE TITLE
[New feature] 天选

### ISSUE THREAD

**Issue by Billyzou0741326** [TheWanderingCoel/BiliBiliHelper#8]
最近用TS重写了一遍监控 新加了天选 
大概是这种格式
```javascript
{
    "id": 65248,
    "roomid": 11437906,
    "category": "anchor",
    "type": "anchor",
    "expireAt": 1579828373,
    "name": "小主播比较穷只能抽0.5元的奖",
    "award_num": 1,
    "gift_name": "",
    "gift_num": 1,
    "gift_price": 0,
    "requirement": "关注主播",
    "danmu": "小主播点个关注吧，关注了就别取消惹，谢谢"
}
```

不过因为一些原因没公开出来 
大佬有时间和意愿写正则筛选参加天选吗？ 有意向的话我给你开放权限吧

**Comment by TheWanderingCoel** [comment]
比较好奇为什么要用到正则,意愿肯定是有的，时间有点紧最近。感谢大佬邀请，有时间我看看。

**Comment by Billyzou0741326** [comment]
邀请了 时间紧没关系hhh我也忙
正则是筛选天选奖励的，毕竟什么奖励都有，筛选出红包不太容易 （我懒23333）

**Comment by TheWanderingCoel** [comment]
谢谢~

**Comment by Billyzou0741326** [comment]
谢什么hhh 客气了
分明是我太懒不想写客户端233

**Comment by TheWanderingCoel** [comment]
hhh我是不会写服务端

**Comment by Billyzou0741326** [comment]
正好正好 合作才是正道

**Comment by TheWanderingCoel** [comment]
嗯

**Comment by TheWanderingCoel** [comment]
感觉天选有点麻烦，又要关注，又要发弹幕，"requirement"的取值只有关注一个么？

**Comment by Billyzou0741326** [comment]
目前见过的requirement有 `关注主播`、`无`、`当前主播粉丝勋章至少x级`，还有个舰长的我忘了具体格式...
天选确实超麻烦2333

**Comment by TheWanderingCoel** [comment]
慢慢来了

**Comment by Billyzou0741326** [comment]
划水划水

**Comment by TheWanderingCoel** [comment]
这个Issue还是先开着吧
请问下大佬天选只需要发弹幕并满足条件就可以参与了嘛，还是需要post接口?

**Comment by Billyzou0741326** [comment]
有个POST的API，我没抓过包，一直是手动参加的2333
不太确定不POST能不能参加

**Comment by TheWanderingCoel** [comment]
手动可以直接发弹幕么还是必须点那个按钮?

**Comment by Billyzou0741326** [comment]
我是点一键参与的  好像也没有特别稳的方法测试手动达成条件能不能参与
要测试的话就要想办法完全避免其它号参与...

**Comment by TheWanderingCoel** [comment]
哎,我看看吧

**Comment by 2438175594** [comment]
这个好像可以https://github.com/lkeme/BiliHelper-personal/blob/master/src/plugin/AnchorRaffle.php

**Comment by TheWanderingCoel** [comment]
感谢，有空研究下

**Comment by Billyzou0741326** [comment]
嗯对 可以像lkeme大佬一样 筛选掉不是抽奖的标题
也可以稳一点 匹配肯定是红包的 这个就要正则了...
我太菜了不会php23333

**Comment by TheWanderingCoel** [comment]
> 嗯对 可以像lkeme大佬一样 筛选掉不是抽奖的标题
> 也可以稳一点 匹配肯定是红包的 这个就要正则了...
> 我太菜了不会php23333

的确,也有可能会有B站钓鱼的

**Comment by lovezm** [comment]
天选api
https://api.live.bilibili.com/xlive/lottery-interface/v1/Anchor/Join
data
id=xxxx&platform=pc&csrf_token=&csrf=&visit_id=
不管是关注还是发弹幕还是送礼物啥的 貌似只需要传入id就可以参与了。

**Comment by Billyzou0741326** [comment]
OK 我wiki会跟进一下 顺便抓一下app端的

**Comment by Billyzou0741326** [comment]
## 天选参与

Method: **POST**   
<https://api.live.bilibili.com/xlive/lottery-interface/v1/Anchor/Join>

| namd              | ps                    |
|-------------------|-----------------------|
| id                | 抽奖号                |
| platform          | pc                    |
| csrf_token        | cookies之一           |
| csrf              | cookies之一           |
| visit_id          |                       |



天选返回值
```javascript
// 成功
{
    "code": 0,
    "data": null,
    "message": "",
    "msg": ""
}
```

**Comment by TheWanderingCoel** [comment]
@lovezm @Billyzou0741326 感谢二位大佬

**Comment by TheWanderingCoel** [comment]
大家有没有想过参与完了，怎么知道什么时候开奖呢，感觉参与完的函数没有返回开奖时间?

**Comment by Billyzou0741326** [comment]
问得好hhh忘了提这个了
考虑过这个 感觉服务器推送不太合适

expireAt参数的价值就体现在这里了吧
`expireAt - time.time()`就是距离开奖的秒数了（不受时区影响）
不过我没抓过开奖api查询 不太清楚是不是同一个 晚点看看吧

**Comment by TheWanderingCoel** [comment]
> 问得好hhh忘了提这个了
> 考虑过这个 感觉服务器推送不太合适
> 
> expireAt参数的价值就体现在这里了吧
> `expireAt - time.time()`就是距离开奖的秒数了（不受时区影响）
> 不过我没抓过开奖api查询 不太清楚是不是同一个 晚点看看吧

我先试试expireAt,谢谢大佬了

**Comment by Billyzou0741326** [comment]
不用不用hhh
我去抓api

**Comment by TheWanderingCoel** [comment]
感谢大佬，辛苦了

**Comment by Billyzou0741326** [comment]
想了下 直接查询中奖记录吧
<https://api.live.bilibili.com/xlive/lottery-interface/v1/Anchor/AwardRecord?page=1>

**Comment by TheWanderingCoel** [comment]
> 想了下 直接查询中奖记录吧
> https://api.live.bilibili.com/xlive/lottery-interface/v1/Anchor/AwardRecord?page=1

也可以，谢谢大佬了，我有空想下怎么做

**Comment by Billyzou0741326** [comment]
不急hhh 我也差不多该冲pk数据了

**Comment by TheWanderingCoel** [comment]
> 不急hhh 我也差不多该冲pk数据了

我pk也没搞完hhh,等大佬wiki搞好2333

**Comment by TheWanderingCoel** [comment]
抓了下Check的接口,感觉一应俱全,我觉得ok。
```json
{
    "code": 0,
    "data": {
        "id": 74344,
        "room_id": 5101555,
        "status": 1,
        "asset_icon": "https://i0.hdslb.com/bfs/live/992c2ccf88d3ea99620fb3a75e672e0abe850e9c.png",
        "award_name": "1元红包 ",
        "award_num": 1,
        "award_image": "",
        "danmu": "",
        "time": 0,
        "current_time": 1580366747,
        "join_type": 0,
        "require_type": 1,
        "require_value": 0,
        "require_text": "关注主播",
        "gift_id": 0,
        "gift_name": "",
        "gift_num": 1,
        "gift_price": 0,
        "cur_gift_num": 0,
        "goaway_time": 170,
        "award_users": [
            {
                "uid": 499857918,
                "uname": "只为你财",
                "face": "http://i2.hdslb.com/bfs/face/d24833754c74aa8f66eb73b7be5966d3143fba56.png",
                "level": 0,
                "color": 9868950
            }
        ],
        "show_panel": 1,
        "url": "https://live.bilibili.com/p/html/live-lottery/anchor-join.html?is_live_half_webview=1\u0026hybrid_biz=live-lottery-anchor\u0026hybrid_half_ui=1,5,100p,100p,000000,0,30,0,0,1;2,5,100p,100p,000000,0,30,0,0,1;3,5,100p,100p,000000,0,30,0,0,1;4,5,100p,100p,000000,0,30,0,0,1;5,5,100p,100p,000000,0,30,0,0,1;6,5,100p,100p,000000,0,30,0,0,1;7,5,100p,100p,000000,0,30,0,0,1;8,5,100p,100p,000000,0,30,0,0,1",
        "lot_status": 2,
        "web_url": "https://live.bilibili.com/p/html/live-lottery/anchor-join.html",
        "send_gift_ensure": 0
    },
    "message": "ok",
    "msg": "ok"
}
```

**Comment by Billyzou0741326** [comment]
好 怎么方便怎么来2333

**Comment by TheWanderingCoel** [comment]
话说大佬,那个expireAt是指天选公布结果还是消失？

**Comment by Billyzou0741326** [comment]
是指正常情况下的公布结果
我记得up是可以提前结束天选的... 不过这种可能性极小

**Comment by TheWanderingCoel** [comment]
> 是指正常情况下的公布结果
> 我记得up是可以提前结束天选的... 不过这种可能性极小

嗯，谢谢大佬了

**Comment by Billyzou0741326** [comment]
这逻辑复杂 其实是麻烦大佬你了hhh
我全程划水2333

**Comment by TheWanderingCoel** [comment]
没有,大佬的监听服务器敲好用的

**Comment by Billyzou0741326** [comment]
⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

**Comment by Billyzou0741326** [comment]
> 我pk也没搞完hhh,等大佬wiki搞好2333

今天一看才发现 pk参与以前我抓过 主要是监控端的缺失

**Comment by Billyzou0741326** [comment]
然后发现JS版也推pk 不过是用http的API查询的 不是最优...

**Comment by Billyzou0741326** [comment]
```python
import re

def is_cash(name):
    cash = re.compile('.*(毛|元|rmb|RMB|块|红包).*')
    return cash.match(name) is not None
```
正则

**Comment by TheWanderingCoel** [comment]
> ```python
> import re
> 
> def is_cash(name):
>     cash = re.compile('.*(毛|元|rmb|RMB|块|红包).*')
>     return cash.match(name) is not None
> ```
> 
> 正则

感谢

**Comment by TheWanderingCoel** [comment]
话说大佬，PK的Check API是啥呢...

**Comment by Billyzou0741326** [comment]
刚醒2333

app端的所有抽奖都用这个API查询<http://api.live.bilibili.com/xlive/lottery-interface/v1/lottery/getLotteryInfo> 所以wiki里我只放了app的

web端小电视、风暴、天选、pk这些查询是分开的
这个是pk的`https://api.live.bilibili.com/xlive/lottery-interface/v1/lottery/Check?roomid={real_roomid}`

**Comment by TheWanderingCoel** [comment]
感谢，正在测试天选和PK了。才发现大佬在美国，我还特意给大佬发了封邮件问这个问题

**Comment by Billyzou0741326** [comment]
慢慢测hhh不急不急 我也划水
